{
 "title": "Operator_CycleTime",
 "description": "Seq 50 Operator 1 and Seq 51 Operator 2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Operator 1 Average Load Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "production",
     "rawSql": "SELECT \r\n    'CV500_545Unload' as metric,\r\n    ROUND(AVG(cycle_time_seconds)::numeric, 2) as value\r\nFROM cycle_times\r\nWHERE \r\n    sequence_id = 31\r\n    AND time >= NOW() - INTERVAL '1 min';"
    }
   ]
  },
  {
   "title": "Operator 2 Average Load Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "production",
     "rawSql": "SELECT \r\n    'CV500_502Load' as metric,\r\n    ROUND(AVG(cycle_time_seconds)::numeric, 2) as value\r\nFROM cycle_times\r\nWHERE \r\n    sequence_id = 5\r\n    AND time >= NOW() - INTERVAL '1 min';"
    }
   ]
  },
  {
   "title": "Operator1 CycleTime",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    time,\r\n    cycle_time_seconds,\r\n    CASE \r\n        WHEN sequence_id = 50 THEN 'Operator 1 (Seq 50)'\r\n    END as metric\r\nFROM cycle_times\r\nWHERE sequence_id IN (50)\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Operator2 CycleTime",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    time,\r\n    cycle_time_seconds,\r\n    CASE \r\n        WHEN sequence_id = 51 THEN 'Operator 2 (Seq 51)'\r\n    END as metric\r\nFROM cycle_times\r\nWHERE sequence_id IN (51)\r\nORDER BY time;"
    }
   ]
  }
 ]
}